name: tcre-assessment
channels:
  - conda-forge
dependencies:
  - python=3.13
  #- conda=25.7.0
  - setuptools
  - pip
  - wheel
  #- conda-anaconda-telemetry
  #- conda-anaconda-tos[version='>=0.1.3']
  #- conda-content-trust
  #- conda-libmamba-solver
  #- menuinst
  #- anaconda-anon-usage
  - jupyter
  - pymc
  - numpy
  - xarray
  - matplotlib
  - seaborn
  - arviz
  - pandas
  - pdfplumber
  - netcdf4
  - jupytext
  - ipykernel
